
int isTmin(int);
int test_isTmin(int);
int bitXor(int, int);
int test_bitXor(int, int);
int allOddBits();
int test_allOddBits();
int sign(int);
int test_sign(int);
int allEvenBits();
int test_allEvenBits();
int getByte(int, int);
int test_getByte(int, int);
int isNonNegative(int);
int test_isNonNegative(int);
int rotateRight(int, int);
int test_rotateRight(int, int);
int isPower2(int);
int test_isPower2(int);
int sm2tc(int);
int test_sm2tc(int);
int howManyBits(int);
int test_howManyBits(int);
